(()=>{"use strict";
const KEY="aku_groq_api_key_v1",MODEL_CODE="openai/gpt-oss-20b",MODEL_CHAT="llama-3.1-8b-instant",STORE="aku_workspace_v1",SESS="aku_sessions_v1";
const $=id=>document.getElementById(id);
let state=JSON.parse(localStorage.getItem(STORE)||'null')||{files:{},messages:[],mode:"code"};
let sessions=JSON.parse(localStorage.getItem(SESS)||"[]");let controller=null;
function save(){localStorage.setItem(STORE,JSON.stringify(state));localStorage.setItem(SESS,JSON.stringify(sessions))}
function esc(s){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function md(s){return esc(s).replace(/\`\`\`([\s\S]*?)\`\`\`/g,"<pre><code>$1</code></pre>").replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>").replace(/\n/g,"<br>")}
function renderMessages(){const box=$("messages");if(!state.messages.length){box.innerHTML='<div class="empty">Start a conversation. Ask for a feature, a fix, or a complete web project.</div>';return}box.innerHTML=state.messages.map(m=>'<div class="msg '+m.role+'"><div class="bubble">'+(m.role==="assistant"?md(m.content):esc(m.content))+'</div></div>').join("");box.scrollTop=box.scrollHeight}
function renderFiles(){const list=$("fileList"),keys=Object.keys(state.files).sort();list.innerHTML=keys.length?keys.map(k=>'<div class="file" title="'+esc(k)+'">'+esc(k)+'</div>').join(""):'<div class="empty" style="padding:24px 8px">No files yet</div>';updatePreview()}
function persistSession(){const title=(state.messages.find(x=>x.role==="user")?.content||"New chat").slice(0,42);sessions=sessions.filter(s=>s.id!==state.id);sessions.unshift({id:state.id,title});sessions=sessions.slice(0,30);save();renderSessions()}
function renderSessions(){const box=$("sessions");box.innerHTML=sessions.map(s=>'<div class="session '+(s.id===state.id?"active":"")+'" data-id="'+s.id+'">'+esc(s.title)+'</div>').join("");box.querySelectorAll(".session").forEach(x=>x.onclick=()=>{const raw=localStorage.getItem("aku_session_"+x.dataset.id);if(raw){state=JSON.parse(raw);save();renderAll()}})}
function archiveSession(){if(state.id)localStorage.setItem("aku_session_"+state.id,JSON.stringify(state));persistSession()}
function newChat(){archiveSession();state={id:crypto.randomUUID(),files:{},messages:[],mode:state.mode};save();renderAll();$("prompt").focus()}
function renderAll(){renderMessages();renderFiles();renderSessions();setMode(state.mode);$("context").textContent=Object.keys(state.files).length?Object.keys(state.files).length+" project files loaded":"No project context loaded"}
function setMode(mode){state.mode=mode;$("codeMode").classList.toggle("active",mode==="code");$("chatMode").classList.toggle("active",mode==="chat");$("modeNote").textContent=mode==="code"?"Edits workspace files and updates preview":"General coding help without changing files";$("prompt").placeholder=mode==="code"?"Describe what you want to build or change…":"Ask a coding question…";save()}
function systemPrompt(){if(state.mode==="code")return "You are Aku Code, an AI coding agent inside a browser workspace. You can stream responses, read project files supplied in the conversation, and create or modify workspace files ONLY by returning blocks in this exact format: [[FILE:path/to/file]] followed by a fenced code block containing the COMPLETE file. You can update multiple files. The browser automatically renders HTML/CSS/JS files in a sandboxed live preview. You do NOT have a terminal, npm runtime, server process, GitHub write access, or Render access. Never claim hidden capabilities. Preserve existing files unless the user asks to remove them. Be concise and implement the requested change.";return "You are Aku Code, a helpful coding assistant. Answer clearly with practical code and explanations. You do not have terminal, server, GitHub write, or deployment access."}
function context(){return Object.entries(state.files).map(([p,c])=>"FILE: "+p+"\n"+c).join("\n\n")}
function extractFiles(text){const re=/\[\[FILE:([^\]]+)\]\]\s*\n\s*\x60\x60\x60[^\n]*\n([\s\S]*?)\n\x60\x60\x60/g;let m,changed=false;while((m=re.exec(text))){state.files[m[1].trim()]=m[2];changed=true}return changed}
function updatePreview(){const html=state.files["index.html"]||state.files["src/index.html"];if(!html){$("preview").srcdoc='<div style="font:14px system-ui;padding:24px;color:#555">Create an index.html file to see your project here.</div>';$("previewState").textContent="Waiting";return}let out=html;const css=state.files["style.css"]||state.files["src/style.css"];const js=state.files["script.js"]||state.files["src/script.js"];if(css&&!out.includes("style.css"))out=out.replace("</head>","<style>"+css.replace(/<\/style>/gi,"")+"</style></head>");if(js&&!out.includes("script.js"))out=out.replace("</body>","<script>"+js.replace(/<\/script>/gi,"")+"</script></body>");$("preview").srcdoc=out;$("previewState").textContent="Live"}
async function ask(prompt){const key=sessionStorage.getItem(KEY)||localStorage.getItem(KEY);if(!key){$("status").textContent="Add your Groq key in Settings";return}state.messages.push({role:"user",content:prompt});renderMessages();persistSession();$("status").textContent="Thinking…";$("stopBtn").hidden=false;controller=new AbortController();const msgs=[{role:"system",content:systemPrompt()}];if(state.mode==="code"&&Object.keys(state.files).length)msgs.push({role:"user",content:"Current workspace files:\n\n"+context()});msgs.push(...state.messages.slice(-12));let answer="";try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:state.mode==="code"?MODEL_CODE:MODEL_CHAT,messages:msgs,temperature:.2,stream:true,max_tokens:4096})});if(!r.ok)throw new Error("Groq request failed ("+r.status+")");const reader=r.body.getReader(),dec=new TextDecoder();state.messages.push({role:"assistant",content:""});renderMessages();while(true){const {value,done}=await reader.read();if(done)break;for(const line of dec.decode(value,{stream:true}).split("\n")){if(!line.startsWith("data: "))continue;const data=line.slice(6);if(data==="[DONE]")continue;try{const j=JSON.parse(data);const d=j.choices?.[0]?.delta?.content||"";if(d){answer+=d;state.messages[state.messages.length-1].content=answer;renderMessages();if(state.mode==="code"&&extractFiles(answer))renderFiles()}}catch{}}}if(state.mode==="code")extractFiles(answer);renderFiles();archiveSession();$("status").textContent="Ready"}catch(e){if(e.name!=="AbortError"){state.messages.push({role:"assistant",content:"Error: "+e.message});renderMessages();$("status").textContent="Error"}}finally{$("stopBtn").hidden=true;controller=null;save()}}
$("composer").onsubmit=e=>{e.preventDefault();const p=$("prompt").value.trim();if(!p)return;$("prompt").value="";ask(p)};$("prompt").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("composer").requestSubmit()}};$("stopBtn").onclick=()=>controller?.abort();$("codeMode").onclick=()=>setMode("code");$("chatMode").onclick=()=>setMode("chat");$("newChat").onclick=newChat;
$("clearFiles").onclick=()=>{state.files={};save();renderAll()};$("uploadBtn").onclick=()=>$("zipInput").click();$("zipInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;const zip=await JSZip.loadAsync(file);for(const name of Object.keys(zip.files)){const z=zip.files[name];if(!z.dir&&!name.startsWith("node_modules/")&&!name.startsWith(".git/"))state.files[name]=await z.async("string")}save();renderFiles();$("status").textContent="ZIP imported"};
$("saveGroq").onclick=()=>{const v=$("groqKey").value.trim();if(!v){$("keyState").textContent="Enter a key first.";return}const target=$("rememberGroq").checked?localStorage:sessionStorage;target.setItem(KEY,v);$("keyState").textContent="Key saved for this browser.";$("groqKey").value=""};$("clearGroq").onclick=()=>{localStorage.removeItem(KEY);sessionStorage.removeItem(KEY);$("keyState").textContent="Key cleared."};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("workspacePage").classList.toggle("hidden",b.dataset.page!=="workspace");$("settingsPage").classList.toggle("hidden",b.dataset.page!=="settings");$("aboutPage").classList.toggle("hidden",b.dataset.page!=="about")});
if(!state.id)state.id=crypto.randomUUID();renderAll();})();